meta_product_name: "Flxibl"
meta_title: "Flxibl | Efficient Freelance Management"
meta_description: "Reduce your headcount and headache by building your very own freelance workforce. Flxibl is the most efficient way to manage your network of freelancers. Sign up for free today."
meta_image: "cover.png" # should exist in `app/assets/images/`
